import { DOLL_CONFIG, state, exportStateJSON } from './state.js';
import { localImageCache, localBlobCache } from './render.js';
import { downloadBlob } from './utils.js';

export function generateConfigJSString() {
  if (!DOLL_CONFIG.defaults) DOLL_CONFIG.defaults = {};
  DOLL_CONFIG.defaults.offsets = state.offsets;

  return `// Dynamic Paper Doll Studio Configuration
// Automatically generated by Paper Doll Studio Client

window.DOLL_CONFIG = ${JSON.stringify(DOLL_CONFIG, null, 2)};
`;
}

export function downloadConfig() {
  const configStr = generateConfigJSString();
  const blob = new Blob([configStr], { type: 'application/javascript;charset=utf-8' });
  downloadBlob(blob, 'doll_config.js');
}

export function downloadStateJSON() {
  const jsonStr = exportStateJSON();
  const blob = new Blob([jsonStr], { type: 'application/json;charset=utf-8' });
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  downloadBlob(blob, `paperdoll-state-${timestamp}.json`);
}

export async function exportZIP(onProgress) {
  const JSZip = window.JSZip;
  if (!JSZip) throw new Error('JSZip library not loaded');

  const zip = new JSZip();

  // Config
  zip.file('doll_config.js', generateConfigJSString());
  zip.file('project.json', JSON.stringify({
    version: 1,
    canvas: DOLL_CONFIG.canvas,
    layers: DOLL_CONFIG.layers,
    wardrobe: DOLL_CONFIG.wardrobe,
    defaults: DOLL_CONFIG.defaults,
    meta: { ...(DOLL_CONFIG.meta || {}), updatedAt: new Date().toISOString() }
  }, null, 2));

  // Assets
  const assetsFolder = zip.folder('public/assets');
  let processed = 0;
  const total = DOLL_CONFIG.layers.length;

  for (const layer of DOLL_CONFIG.layers) {
    const filename = layer.file;
    if (localBlobCache[filename]) {
      assetsFolder.file(filename, localBlobCache[filename]);
    } else {
      try {
        const response = await fetch(`public/assets/${filename}`);
        if (response.ok) {
          const blob = await response.blob();
          assetsFolder.file(filename, blob);
        } else {
          console.warn(`Could not fetch public/assets/${filename} from server.`);
        }
      } catch (err) {
        console.error(`Error fetching asset ${filename}:`, err);
      }
    }
    processed++;
    if (onProgress) onProgress(processed, total);
  }

  // Include core app files
  // Note: project.json is NOT fetched from the server here because it is
  // dynamically generated above with the current DOLL_CONFIG (which includes
  // any compiled-asset wardrobe entries).  Fetching the static server copy
  // would overwrite those dynamic changes.
  try {
    const files = ['index.html', 'style.css'];
    for (const f of files) {
      const res = await fetch(f);
      if (res.ok) zip.file(f, await res.blob());
    }
    // Add wardrobe manifest and every compiled asset folder it references
    let manifest = [];
    try {
      const manifestRes = await fetch('public/assets/wardrobe_manifest.json');
      if (manifestRes.ok) {
        const manifestBlob = await manifestRes.blob();
        assetsFolder.file('wardrobe_manifest.json', manifestBlob);
        manifest = JSON.parse(await manifestBlob.text());
      }
    } catch (err) {
      console.warn('Could not include wardrobe_manifest.json:', err);
    }
    for (const entry of manifest) {
      const cat = entry.category;
      const aid = entry.asset_id;
      if (!cat || !aid) continue;
      const base = `compiled/${cat}/${aid}`;
      // metadata.json (drives per-layer list below)
      let metadata = null;
      try {
        const mRes = await fetch(`public/assets/${base}/metadata.json`);
        if (mRes.ok) {
          const mBlob = await mRes.blob();
          assetsFolder.file(`${base}/metadata.json`, mBlob);
          metadata = JSON.parse(await mBlob.text());
        }
      } catch (err) {
        console.warn(`Could not include ${base}/metadata.json:`, err);
      }
      // preview.png
      try {
        const pRes = await fetch(`public/assets/${base}/preview.png`);
        if (pRes.ok) assetsFolder.file(`${base}/preview.png`, await pRes.blob());
      } catch (err) {
        console.warn(`Could not include ${base}/preview.png:`, err);
      }
      // per-layer PNGs from metadata.layers[].file
      if (metadata && Array.isArray(metadata.layers)) {
        for (const layer of metadata.layers) {
          if (!layer.file) continue;
          try {
            const lRes = await fetch(`public/assets/${base}/${layer.file}`);
            if (lRes.ok) assetsFolder.file(`${base}/${layer.file}`, await lRes.blob());
          } catch (err) {
            console.warn(`Could not include ${base}/${layer.file}:`, err);
          }
        }
      }
      // fit_debug/anchors.json (best effort; non-fitted categories won't have it)
      try {
        const aRes = await fetch(`public/assets/${base}/fit_debug/anchors.json`);
        if (aRes.ok) assetsFolder.file(`${base}/fit_debug/anchors.json`, await aRes.blob());
      } catch (err) {
        /* expected for non-fitted categories */
      }
    }
    // Add JS modules
    const moduleFiles = ['js/utils.js', 'js/state.js', 'js/render.js', 'js/wardrobe.js', 'js/calibration.js', 'js/import.js', 'js/export.js', 'app.js'];
    for (const f of moduleFiles) {
      const res = await fetch(f);
      if (res.ok) zip.file(f, await res.blob());
    }
  } catch (err) {
    console.warn('Could not include core app files in ZIP:', err);
  }

  const zipContent = await zip.generateAsync({ type: 'blob' });
  downloadBlob(zipContent, 'paperdoll_project.zip');
  return zipContent;
}
