// Paper Doll Studio Configuration
// Generated by PSD adapter

window.DOLL_CONFIG = {
  "canvas": {
    "width": 768,
    "height": 768
  },
  "layers": [
    {
      "id": "hair_back",
      "name": "hair_back",
      "file": "hair_back.png",
      "z": 10,
      "visible": true,
      "category": "hair",
      "subcategory": "hair_back",
      "toggleable": true,
      "dyeable": true
    },
    {
      "id": "body_neck",
      "name": "body_neck",
      "file": "body_neck.png",
      "z": 20,
      "visible": true,
      "category": "face",
      "subcategory": "neck"
    },
    {
      "id": "body_ears_l",
      "name": "body_ears_l",
      "file": "body_ears_l.png",
      "z": 30,
      "visible": true,
      "category": "face",
      "subcategory": "ears",
      "toggleable": true
    },
    {
      "id": "body_ears_r",
      "name": "body_ears_r",
      "file": "body_ears_r.png",
      "z": 40,
      "visible": true,
      "category": "face",
      "subcategory": "ears",
      "toggleable": true
    },
    {
      "id": "body_face",
      "name": "body_face",
      "file": "body_face.png",
      "z": 50,
      "visible": true,
      "category": "face",
      "subcategory": "face"
    },
    {
      "id": "eyes_white_l",
      "name": "eyes_white_l",
      "file": "eyes_white_l.png",
      "z": 60,
      "visible": true,
      "category": "eyes",
      "subcategory": "eyewhite",
      "toggleable": true
    },
    {
      "id": "eyes_white_r",
      "name": "eyes_white_r",
      "file": "eyes_white_r.png",
      "z": 70,
      "visible": true,
      "category": "eyes",
      "subcategory": "eyewhite",
      "toggleable": true
    },
    {
      "id": "eyes_irides_l",
      "name": "eyes_irides_l",
      "file": "eyes_irides_l.png",
      "z": 80,
      "visible": true,
      "category": "eyes",
      "subcategory": "irides",
      "toggleable": true,
      "dyeable": true
    },
    {
      "id": "eyes_irides_r",
      "name": "eyes_irides_r",
      "file": "eyes_irides_r.png",
      "z": 90,
      "visible": true,
      "category": "eyes",
      "subcategory": "irides",
      "toggleable": true,
      "dyeable": true
    },
    {
      "id": "eyes_eyelash_l",
      "name": "eyes_eyelash_l",
      "file": "eyes_eyelash_l.png",
      "z": 100,
      "visible": true,
      "category": "eyes",
      "subcategory": "eyelashes",
      "toggleable": true
    },
    {
      "id": "eyes_eyelash_r",
      "name": "eyes_eyelash_r",
      "file": "eyes_eyelash_r.png",
      "z": 110,
      "visible": true,
      "category": "eyes",
      "subcategory": "eyelashes",
      "toggleable": true
    },
    {
      "id": "eyes_eyebrow_l",
      "name": "eyes_eyebrow_l",
      "file": "eyes_eyebrow_l.png",
      "z": 120,
      "visible": true,
      "category": "eyes",
      "subcategory": "eyebrows",
      "toggleable": true
    },
    {
      "id": "eyes_eyebrow_r",
      "name": "eyes_eyebrow_r",
      "file": "eyes_eyebrow_r.png",
      "z": 130,
      "visible": true,
      "category": "eyes",
      "subcategory": "eyebrows",
      "toggleable": true
    },
    {
      "id": "body_nose",
      "name": "body_nose",
      "file": "body_nose.png",
      "z": 140,
      "visible": true,
      "category": "face",
      "subcategory": "nose",
      "toggleable": true
    },
    {
      "id": "body_mouth",
      "name": "body_mouth",
      "file": "body_mouth.png",
      "z": 150,
      "visible": true,
      "category": "face",
      "subcategory": "mouth",
      "toggleable": true
    },
    {
      "id": "hair_front",
      "name": "hair_front",
      "file": "hair_front.png",
      "z": 160,
      "visible": true,
      "category": "hair",
      "subcategory": "hair_front",
      "toggleable": true,
      "dyeable": true
    },
    {
      "id": "skin_wear_top",
      "name": "skin_wear_top",
      "file": "skin_wear_top.png",
      "z": 170,
      "visible": true,
      "category": "wardrobe",
      "subcategory": "topwear",
      "optionValue": "skin_wear"
    },
    {
      "id": "skin_wear_dress",
      "name": "skin_wear_dress",
      "file": "skin_wear_dress.png",
      "z": 175,
      "visible": false,
      "category": "wardrobe",
      "subcategory": "dress",
      "optionValue": "skin_wear"
    },
    {
      "id": "skin_wear_bottom",
      "name": "skin_wear_bottom",
      "file": "skin_wear_bottom.png",
      "z": 180,
      "visible": true,
      "category": "wardrobe",
      "subcategory": "bottomwear",
      "optionValue": "skin_wear"
    },
    {
      "id": "skin_wear_skirt",
      "name": "skin_wear_skirt",
      "file": "skin_wear_skirt.png",
      "z": 185,
      "visible": false,
      "category": "wardrobe",
      "subcategory": "skirt",
      "optionValue": "skin_wear"
    },
    {
      "id": "skin_wear_legs",
      "name": "skin_wear_legs",
      "file": "skin_wear_legs.png",
      "z": 190,
      "visible": true,
      "category": "wardrobe",
      "subcategory": "legwear",
      "optionValue": "skin_wear"
    },
    {
      "id": "skin_wear_hands",
      "name": "skin_wear_hands",
      "file": "skin_wear_hands.png",
      "z": 195,
      "visible": true,
      "category": "wardrobe",
      "subcategory": "handwear",
      "optionValue": "skin_wear"
    },
    {
      "id": "skin_wear_outerwear",
      "name": "skin_wear_outerwear",
      "file": "skin_wear_outerwear.png",
      "z": 197,
      "visible": false,
      "category": "wardrobe",
      "subcategory": "outerwear",
      "optionValue": "skin_wear"
    },
    {
      "id": "skin_wear_shoes",
      "name": "skin_wear_shoes",
      "file": "skin_wear_shoes.png",
      "z": 198,
      "visible": false,
      "category": "wardrobe",
      "subcategory": "shoes",
      "optionValue": "skin_wear"
    },
    {
      "id": "skin_wear_accessory",
      "name": "skin_wear_accessory",
      "file": "skin_wear_accessory.png",
      "z": 199,
      "visible": false,
      "category": "wardrobe",
      "subcategory": "accessory",
      "optionValue": "skin_wear"
    },
    {
      "id": "clothing_dress",
      "name": "clothing_dress",
      "file": "clothing_dress.png",
      "z": 205,
      "visible": false,
      "category": "wardrobe",
      "subcategory": "dress",
      "optionValue": "clothing"
    },
    {
      "id": "clothing_topwear",
      "name": "clothing_topwear",
      "file": "clothing_topwear.png",
      "z": 210,
      "visible": true,
      "category": "wardrobe",
      "subcategory": "topwear",
      "optionValue": "clothing"
    },
    {
      "id": "clothing_outerwear",
      "name": "clothing_outerwear",
      "file": "clothing_outerwear.png",
      "z": 215,
      "visible": false,
      "category": "wardrobe",
      "subcategory": "outerwear",
      "optionValue": "clothing"
    },
    {
      "id": "clothing_bottomwear",
      "name": "clothing_bottomwear",
      "file": "clothing_bottomwear.png",
      "z": 220,
      "visible": true,
      "category": "wardrobe",
      "subcategory": "bottomwear",
      "optionValue": "clothing"
    },
    {
      "id": "clothing_skirt",
      "name": "clothing_skirt",
      "file": "clothing_skirt.png",
      "z": 225,
      "visible": false,
      "category": "wardrobe",
      "subcategory": "skirt",
      "optionValue": "clothing"
    },
    {
      "id": "clothing_legwear",
      "name": "clothing_legwear",
      "file": "clothing_legwear.png",
      "z": 230,
      "visible": true,
      "category": "wardrobe",
      "subcategory": "legwear",
      "optionValue": "clothing"
    },
    {
      "id": "clothing_shoes",
      "name": "clothing_shoes",
      "file": "clothing_shoes.png",
      "z": 235,
      "visible": false,
      "category": "wardrobe",
      "subcategory": "shoes",
      "optionValue": "clothing"
    },
    {
      "id": "clothing_handwear_l",
      "name": "clothing_handwear_l",
      "file": "clothing_handwear_l.png",
      "z": 240,
      "visible": true,
      "category": "wardrobe",
      "subcategory": "handwear",
      "optionValue": "clothing"
    },
    {
      "id": "clothing_accessory",
      "name": "clothing_accessory",
      "file": "clothing_accessory.png",
      "z": 245,
      "visible": false,
      "category": "wardrobe",
      "subcategory": "accessory",
      "optionValue": "clothing"
    },
    {
      "id": "clothing_handwear_r",
      "name": "clothing_handwear_r",
      "file": "clothing_handwear_r.png",
      "z": 250,
      "visible": true,
      "category": "wardrobe",
      "subcategory": "handwear",
      "optionValue": "clothing"
    }
  ],
  "wardrobe": {
    "dress": {
      "name": "Dress",
      "options": [
        {
          "value": "none",
          "name": "Invisible / None",
          "layers": []
        }
      ],
      "defaultValue": "none"
    },
    "topwear": {
      "name": "Topwear",
      "options": [
        {
          "value": "skin_wear",
          "name": "Naked / Skin Wear",
          "layers": [
            "skin_wear_top"
          ]
        },
        {
          "value": "clothing",
          "name": "Topwear",
          "layers": [
            "skin_wear_top",
            "clothing_topwear"
          ]
        },
        {
          "value": "none",
          "name": "Invisible / None",
          "layers": []
        }
      ],
      "defaultValue": "skin_wear"
    },
    "bottomwear": {
      "name": "Bottomwear",
      "options": [
        {
          "value": "skin_wear",
          "name": "Naked / Skin Wear",
          "layers": [
            "skin_wear_bottom"
          ]
        },
        {
          "value": "clothing",
          "name": "Bottomwear",
          "layers": [
            "skin_wear_bottom",
            "clothing_bottomwear"
          ]
        },
        {
          "value": "none",
          "name": "Invisible / None",
          "layers": []
        }
      ],
      "defaultValue": "skin_wear"
    },
    "skirt": {
      "name": "Skirt",
      "options": [
        {
          "value": "none",
          "name": "Invisible / None",
          "layers": []
        }
      ],
      "defaultValue": "none"
    },
    "pants": {
      "name": "Pants",
      "options": [
        {
          "value": "none",
          "name": "Invisible / None",
          "layers": []
        }
      ],
      "defaultValue": "none"
    },
    "legwear": {
      "name": "Legwear",
      "options": [
        {
          "value": "skin_wear",
          "name": "Naked / Skin Wear",
          "layers": [
            "skin_wear_legs"
          ]
        },
        {
          "value": "clothing",
          "name": "Legwear",
          "layers": [
            "skin_wear_legs",
            "clothing_legwear"
          ]
        },
        {
          "value": "none",
          "name": "Invisible / None",
          "layers": []
        }
      ],
      "defaultValue": "skin_wear"
    },
    "handwear": {
      "name": "Handwear",
      "options": [
        {
          "value": "skin_wear",
          "name": "Naked / Skin Wear",
          "layers": [
            "skin_wear_hands"
          ]
        },
        {
          "value": "clothing",
          "name": "Handwear",
          "layers": [
            "skin_wear_hands",
            "clothing_handwear_l",
            "clothing_handwear_r"
          ]
        },
        {
          "value": "none",
          "name": "Invisible / None",
          "layers": []
        }
      ],
      "defaultValue": "skin_wear"
    },
    "outerwear": {
      "name": "Outerwear",
      "options": [
        {
          "value": "none",
          "name": "Invisible / None",
          "layers": []
        }
      ],
      "defaultValue": "none"
    },
    "shoes": {
      "name": "Shoes",
      "options": [
        {
          "value": "none",
          "name": "Invisible / None",
          "layers": []
        }
      ],
      "defaultValue": "none"
    },
    "accessory": {
      "name": "Accessory",
      "options": [
        {
          "value": "none",
          "name": "Invisible / None",
          "layers": []
        }
      ],
      "defaultValue": "none"
    }
  },
  "defaults": {
    "theme": "dark",
    "zoom": 1.0,
    "showGrid": true
  }
};
